twig:
    default_path: '%kernel.project_dir%/src/View'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/images': images